using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GoldMineScript : MonoBehaviour
{
    
    [Tooltip("Amount of gold per minute generated by the mine")] [SerializeField]
    private int miningSpeed;
    
    // Progress of gold generation 
    private float goldProgress;

    private PlayerStats playerStats;

    private void Start()
    {
        GameEvents.current.Tick += Tick;

        playerStats = GameObject.FindWithTag("Player").GetComponent<PlayerStats>();

        if (playerStats == null) { Debug.Log("GoldMineScript: PlayerStats component not found"); }
    }

    private void OnEnable()
    {
        GameEvents.current.Tick += Tick;
    }

    private void OnDisable()
    {
        GameEvents.current.Tick -= Tick;
    }

    private void Tick(int tick)
    {
        float goldPerTick = miningSpeed / 60f / 20f;    // Assuming tick speed is 20. TODO: implement getter for tick speed
        goldProgress += goldPerTick;
        
        // If one whole unit of gold has been generated, add it to player statistics
        if (goldProgress >= 1)
        {
            int goldToAdd = Mathf.FloorToInt(goldProgress);
            goldProgress -= goldToAdd;
            playerStats.AddGold(goldToAdd); 
        }
    }
}
