using EventSystem;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GoldMineScript : MonoBehaviour
{
    
    [Tooltip("Amount of gold per minute generated by the mine")] [SerializeField]
    private int miningSpeed;
    
    // Progress of gold generation 
    private float goldProgress;

    private PlayerStats playerStats;
    private Tick tickComponent;
    private int tickSpeed;


    private void Start()
    {
        playerStats = GameObject.FindWithTag("Player").GetComponent<PlayerStats>();
        if (playerStats == null) { Debug.Log("GoldMineScript: PlayerStats component not found"); }

        tickComponent = GameObject.Find("Game Event System").GetComponent<Tick>();
        if (tickComponent == null) { Debug.Log("GoldMineScript: Game Event System component not found"); }

        tickSpeed = tickComponent.GetTickSpeed();
    }

    private void OnEnable()
    {
        GameEvents.current.Tick += Tick;
    }

    private void OnDisable()
    {
        GameEvents.current.Tick -= Tick;
    }

    private void Tick(int tick)
    {
        float goldPerTick = miningSpeed / 60f / tickSpeed;
        goldProgress += goldPerTick;
        
        // If one whole unit of gold has been generated, add it to player statistics
        if (goldProgress >= 1)
        {
            int goldToAdd = Mathf.FloorToInt(goldProgress);
            goldProgress -= goldToAdd;
            playerStats.AddGold(goldToAdd); 
        }
    }
    public void AddMiningSpeed(int speed) {
        this.miningSpeed += speed;
    }
}
